/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author espar
 */
public class Frame extends javax.swing.JFrame {


    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_pricipal = new javax.swing.JPanel();
        Contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        EscalaGris = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5_Name = new javax.swing.JLabel();
        jLabel6_Altura = new javax.swing.JLabel();
        jLabel7_Ancho = new javax.swing.JLabel();
        Histograma = new javax.swing.JButton();
        CMY = new javax.swing.JButton();
        HSI_Botton = new javax.swing.JButton();
        Contenedor_Imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Umbralizacion = new javax.swing.JMenu();
        jMenuItem1_Inverso = new javax.swing.JMenuItem();
        jMenuItem2_Operador_Umbral = new javax.swing.JMenuItem();
        jMenuItem3_Operador_Umbral_Inverso = new javax.swing.JMenuItem();
        jMenuItem4_Binario = new javax.swing.JMenuItem();
        jMenuItem5_Binario_Inverso = new javax.swing.JMenuItem();
        jMenuItem6_Umbral_Gris = new javax.swing.JMenuItem();
        jMenuItem7_Umbral_Gris_Inverso = new javax.swing.JMenuItem();
        jMenuItem8_Operador_Extencion = new javax.swing.JMenuItem();
        jMenuItem9_Reduccion_Niveles_Gris = new javax.swing.JMenuItem();
        Operaciones = new javax.swing.JMenu();
        jMenuItem10_Suma = new javax.swing.JMenuItem();
        jMenuItem11_Resta = new javax.swing.JMenuItem();
        jMenuItem12_And = new javax.swing.JMenuItem();
        jMenuItem13_Or = new javax.swing.JMenuItem();
        jMenuItem14_Xort = new javax.swing.JMenuItem();
        jMenuItem15_Rotacion90 = new javax.swing.JMenuItem();
        jMenuItem16_Rotacion180 = new javax.swing.JMenuItem();
        jMenuItem17_Rotacion270 = new javax.swing.JMenuItem();
        Filtros_Espaciales = new javax.swing.JMenu();
        jMenuItem1_Interpolacion = new javax.swing.JMenuItem();
        jMenuItem2_Convolucion = new javax.swing.JMenuItem();
        Filtros_Restauracion = new javax.swing.JMenu();
        jMenuItem1_Media_Aritmetica = new javax.swing.JMenuItem();
        jMenuItem2_Media_Geometrica = new javax.swing.JMenuItem();
        jMenuItem3_Mediana = new javax.swing.JMenuItem();
        jMenuItem4_Maximo = new javax.swing.JMenuItem();
        jMenuItem5_Minimo = new javax.swing.JMenuItem();
        jMenuItem6_Punto_Medio = new javax.swing.JMenuItem();
        jMenuItem7_Media_Seccion = new javax.swing.JMenuItem();
        jMenuItem1_Media_Adaptativo = new javax.swing.JMenuItem();
        Filtros_Frecuencia = new javax.swing.JMenu();
        jMenuItem1_Espectro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_idealLowPassFilter = new javax.swing.JMenuItem();
        jMenuItem1_butterworthLowPassFilter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1_idealHighPassFilter = new javax.swing.JMenuItem();
        jMenuItem1_butterworthHighPassFilter = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1_idealBandPassFilter = new javax.swing.JMenuItem();
        jMenuItem1_idealBandStopFilter = new javax.swing.JMenuItem();
        jMenuItem1_butterworthBandPassFilter = new javax.swing.JMenuItem();
        jMenuItem1_butterworthBandStopFilter = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Morfologicas_Erosion = new javax.swing.JMenuItem();
        Morfologicas_Dilatacion = new javax.swing.JMenuItem();
        Morfologicas_Apertura = new javax.swing.JMenuItem();
        Morfologicas_Cierre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_pricipal.setBackground(new java.awt.Color(0, 0, 0));

        Contenedor.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        Buscar.setBackground(new java.awt.Color(0, 0, 0));
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText(" Buscar una Imagen");

        EscalaGris.setBackground(new java.awt.Color(0, 0, 0));
        EscalaGris.setForeground(new java.awt.Color(255, 255, 255));
        EscalaGris.setText("Aplicar escala de Grises");

        Regresar.setBackground(new java.awt.Color(0, 0, 0));
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar imagen a original");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre de la imagen: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Tamaño de Altura: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Tamaño de Ancho: ");

        jLabel5_Name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel6_Altura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel7_Ancho.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        Histograma.setBackground(new java.awt.Color(0, 0, 0));
        Histograma.setForeground(new java.awt.Color(255, 255, 255));
        Histograma.setText("Histograma");

        CMY.setBackground(new java.awt.Color(0, 0, 0));
        CMY.setForeground(new java.awt.Color(255, 255, 255));
        CMY.setText("RGB A CMY");

        HSI_Botton.setBackground(new java.awt.Color(0, 0, 0));
        HSI_Botton.setForeground(new java.awt.Color(255, 255, 255));
        HSI_Botton.setText("RGB A HSI");
        HSI_Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSI_BottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar)
                            .addComponent(EscalaGris)
                            .addComponent(Regresar))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7_Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Histograma)
                        .addGap(18, 18, 18)
                        .addComponent(CMY)
                        .addGap(18, 18, 18)
                        .addComponent(HSI_Botton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Buscar)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EscalaGris)
                        .addGap(18, 18, 18)
                        .addComponent(Regresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7_Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMY)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Histograma)
                        .addComponent(HSI_Botton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Buscar.getAccessibleContext().setAccessibleDescription("");

        Contenedor_Imagen.setBackground(new java.awt.Color(0, 0, 0));
        Contenedor_Imagen.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Panel_pricipalLayout = new javax.swing.GroupLayout(Panel_pricipal);
        Panel_pricipal.setLayout(Panel_pricipalLayout);
        Panel_pricipalLayout.setHorizontalGroup(
            Panel_pricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_pricipalLayout.createSequentialGroup()
                .addGroup(Panel_pricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_pricipalLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_pricipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(Contenedor_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_pricipalLayout.setVerticalGroup(
            Panel_pricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_pricipalLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(Panel_pricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contenedor_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_pricipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 0));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Umbralizacion.setText("Umbralizacion");
        Umbralizacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1_Inverso.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_Inverso.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_Inverso.setText("Inverso o Negativo");
        jMenuItem1_Inverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_InversoActionPerformed(evt);
            }
        });
        Umbralizacion.add(jMenuItem1_Inverso);

        jMenuItem2_Operador_Umbral.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem2_Operador_Umbral.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2_Operador_Umbral.setText("Operador Umbral");
        jMenuItem2_Operador_Umbral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_Operador_UmbralActionPerformed(evt);
            }
        });
        Umbralizacion.add(jMenuItem2_Operador_Umbral);

        jMenuItem3_Operador_Umbral_Inverso.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem3_Operador_Umbral_Inverso.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3_Operador_Umbral_Inverso.setText("Operador Umbral Inverso");
        Umbralizacion.add(jMenuItem3_Operador_Umbral_Inverso);

        jMenuItem4_Binario.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem4_Binario.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem4_Binario.setText("Umbral Binario");
        Umbralizacion.add(jMenuItem4_Binario);

        jMenuItem5_Binario_Inverso.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem5_Binario_Inverso.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem5_Binario_Inverso.setText("Umbral Binario Inverso");
        Umbralizacion.add(jMenuItem5_Binario_Inverso);

        jMenuItem6_Umbral_Gris.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem6_Umbral_Gris.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem6_Umbral_Gris.setText("Umbral en Gris");
        Umbralizacion.add(jMenuItem6_Umbral_Gris);

        jMenuItem7_Umbral_Gris_Inverso.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem7_Umbral_Gris_Inverso.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7_Umbral_Gris_Inverso.setText("Umbral en Gris inverso");
        Umbralizacion.add(jMenuItem7_Umbral_Gris_Inverso);

        jMenuItem8_Operador_Extencion.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem8_Operador_Extencion.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8_Operador_Extencion.setText("Operador extencion");
        Umbralizacion.add(jMenuItem8_Operador_Extencion);

        jMenuItem9_Reduccion_Niveles_Gris.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem9_Reduccion_Niveles_Gris.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9_Reduccion_Niveles_Gris.setText("Reduccion de niveles de Gris");
        Umbralizacion.add(jMenuItem9_Reduccion_Niveles_Gris);

        jMenuBar1.add(Umbralizacion);

        Operaciones.setText("Operacion");
        Operaciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem10_Suma.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem10_Suma.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem10_Suma.setText("Suma");
        Operaciones.add(jMenuItem10_Suma);

        jMenuItem11_Resta.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem11_Resta.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem11_Resta.setText("Resta");
        jMenuItem11_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11_RestaActionPerformed(evt);
            }
        });
        Operaciones.add(jMenuItem11_Resta);

        jMenuItem12_And.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem12_And.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem12_And.setText("And");
        Operaciones.add(jMenuItem12_And);

        jMenuItem13_Or.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem13_Or.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem13_Or.setText("Or");
        jMenuItem13_Or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13_OrActionPerformed(evt);
            }
        });
        Operaciones.add(jMenuItem13_Or);

        jMenuItem14_Xort.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem14_Xort.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem14_Xort.setText("Xort");
        Operaciones.add(jMenuItem14_Xort);

        jMenuItem15_Rotacion90.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem15_Rotacion90.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem15_Rotacion90.setText("Rotacion 90");
        Operaciones.add(jMenuItem15_Rotacion90);

        jMenuItem16_Rotacion180.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem16_Rotacion180.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem16_Rotacion180.setText("Rotacion 180");
        Operaciones.add(jMenuItem16_Rotacion180);

        jMenuItem17_Rotacion270.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem17_Rotacion270.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem17_Rotacion270.setText("Rotacion 270");
        Operaciones.add(jMenuItem17_Rotacion270);

        jMenuBar1.add(Operaciones);

        Filtros_Espaciales.setText("Filtros Espaciales");
        Filtros_Espaciales.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1_Interpolacion.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_Interpolacion.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_Interpolacion.setText("Interpolacion");
        Filtros_Espaciales.add(jMenuItem1_Interpolacion);

        jMenuItem2_Convolucion.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem2_Convolucion.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2_Convolucion.setText("Convolucion");
        Filtros_Espaciales.add(jMenuItem2_Convolucion);

        jMenuBar1.add(Filtros_Espaciales);

        Filtros_Restauracion.setText("Filtros de Restauracion");
        Filtros_Restauracion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1_Media_Aritmetica.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_Media_Aritmetica.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_Media_Aritmetica.setText("Media Aritmetica");
        Filtros_Restauracion.add(jMenuItem1_Media_Aritmetica);

        jMenuItem2_Media_Geometrica.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem2_Media_Geometrica.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2_Media_Geometrica.setText("Media Geometrica");
        Filtros_Restauracion.add(jMenuItem2_Media_Geometrica);

        jMenuItem3_Mediana.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem3_Mediana.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3_Mediana.setText("Mediana");
        Filtros_Restauracion.add(jMenuItem3_Mediana);

        jMenuItem4_Maximo.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem4_Maximo.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem4_Maximo.setText("Maximo");
        Filtros_Restauracion.add(jMenuItem4_Maximo);

        jMenuItem5_Minimo.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem5_Minimo.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem5_Minimo.setText("Minimo");
        Filtros_Restauracion.add(jMenuItem5_Minimo);

        jMenuItem6_Punto_Medio.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem6_Punto_Medio.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem6_Punto_Medio.setText("Punto Medio");
        Filtros_Restauracion.add(jMenuItem6_Punto_Medio);

        jMenuItem7_Media_Seccion.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem7_Media_Seccion.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7_Media_Seccion.setText("Media Seccion");
        Filtros_Restauracion.add(jMenuItem7_Media_Seccion);

        jMenuItem1_Media_Adaptativo.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_Media_Adaptativo.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_Media_Adaptativo.setText("Media Adaptativo");
        jMenuItem1_Media_Adaptativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_Media_AdaptativoActionPerformed(evt);
            }
        });
        Filtros_Restauracion.add(jMenuItem1_Media_Adaptativo);

        jMenuBar1.add(Filtros_Restauracion);

        Filtros_Frecuencia.setText("Filtros de Frecuencia");
        Filtros_Frecuencia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1_Espectro.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_Espectro.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_Espectro.setText("Espectro");
        Filtros_Frecuencia.add(jMenuItem1_Espectro);

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Low Pass Filtering");

        jMenuItem1_idealLowPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_idealLowPassFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_idealLowPassFilter.setText("Ideal Low PassFilter");
        jMenuItem1_idealLowPassFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_idealLowPassFilterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_idealLowPassFilter);

        jMenuItem1_butterworthLowPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_butterworthLowPassFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_butterworthLowPassFilter.setText("Butterworth Low Pass Filter");
        jMenu1.add(jMenuItem1_butterworthLowPassFilter);

        Filtros_Frecuencia.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(153, 153, 153));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("High Pass Filtering");

        jMenuItem1_idealHighPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_idealHighPassFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_idealHighPassFilter.setText("Ideal High Pass Filtering");
        jMenu2.add(jMenuItem1_idealHighPassFilter);

        jMenuItem1_butterworthHighPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_butterworthHighPassFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_butterworthHighPassFilter.setText("Butterworth High Pass Filter");
        jMenu2.add(jMenuItem1_butterworthHighPassFilter);

        Filtros_Frecuencia.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(153, 153, 153));
        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setText("Band Pass and Stop Filtering");

        jMenuItem1_idealBandPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_idealBandPassFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_idealBandPassFilter.setText("Ideal Band Pass Filter");
        jMenu3.add(jMenuItem1_idealBandPassFilter);

        jMenuItem1_idealBandStopFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_idealBandStopFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_idealBandStopFilter.setText("Ideal Band Stop Filter");
        jMenu3.add(jMenuItem1_idealBandStopFilter);

        jMenuItem1_butterworthBandPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_butterworthBandPassFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_butterworthBandPassFilter.setText("Butterworth Band Pass Filter");
        jMenu3.add(jMenuItem1_butterworthBandPassFilter);

        jMenuItem1_butterworthBandStopFilter.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1_butterworthBandStopFilter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1_butterworthBandStopFilter.setText("Butterworth Band Stop Filter");
        jMenu3.add(jMenuItem1_butterworthBandStopFilter);

        Filtros_Frecuencia.add(jMenu3);

        jMenuBar1.add(Filtros_Frecuencia);

        jMenu4.setText("Operaciones Morfologicas");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        Morfologicas_Erosion.setBackground(new java.awt.Color(0, 0, 0));
        Morfologicas_Erosion.setForeground(new java.awt.Color(255, 255, 255));
        Morfologicas_Erosion.setText("Erosion");
        Morfologicas_Erosion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Morfologicas_ErosionActionPerformed(evt);
            }
        });
        jMenu4.add(Morfologicas_Erosion);

        Morfologicas_Dilatacion.setBackground(new java.awt.Color(0, 0, 0));
        Morfologicas_Dilatacion.setForeground(new java.awt.Color(255, 255, 255));
        Morfologicas_Dilatacion.setText("Dilatacion");
        jMenu4.add(Morfologicas_Dilatacion);

        Morfologicas_Apertura.setBackground(new java.awt.Color(0, 0, 0));
        Morfologicas_Apertura.setForeground(new java.awt.Color(255, 255, 255));
        Morfologicas_Apertura.setText("Apertura");
        jMenu4.add(Morfologicas_Apertura);

        Morfologicas_Cierre.setBackground(new java.awt.Color(0, 0, 0));
        Morfologicas_Cierre.setForeground(new java.awt.Color(255, 255, 255));
        Morfologicas_Cierre.setText("Cierre");
        jMenu4.add(Morfologicas_Cierre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_pricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel_pricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_InversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_InversoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1_InversoActionPerformed

    private void jMenuItem2_Operador_UmbralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_Operador_UmbralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2_Operador_UmbralActionPerformed

    private void jMenuItem11_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11_RestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11_RestaActionPerformed

    private void jMenuItem13_OrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13_OrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13_OrActionPerformed

    private void jMenuItem1_Media_AdaptativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_Media_AdaptativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_Media_AdaptativoActionPerformed

    private void jMenuItem1_idealLowPassFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_idealLowPassFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_idealLowPassFilterActionPerformed

    private void HSI_BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSI_BottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSI_BottonActionPerformed

    private void Morfologicas_ErosionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Morfologicas_ErosionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Morfologicas_ErosionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Buscar;
    public javax.swing.JButton CMY;
    public javax.swing.JPanel Contenedor;
    public javax.swing.JLabel Contenedor_Imagen;
    public javax.swing.JButton EscalaGris;
    public javax.swing.JMenu Filtros_Espaciales;
    public javax.swing.JMenu Filtros_Frecuencia;
    public javax.swing.JMenu Filtros_Restauracion;
    public javax.swing.JButton HSI_Botton;
    public javax.swing.JButton Histograma;
    public javax.swing.JMenuItem Morfologicas_Apertura;
    public javax.swing.JMenuItem Morfologicas_Cierre;
    public javax.swing.JMenuItem Morfologicas_Dilatacion;
    public javax.swing.JMenuItem Morfologicas_Erosion;
    public javax.swing.JMenu Operaciones;
    public javax.swing.JPanel Panel_pricipal;
    public javax.swing.JButton Regresar;
    public javax.swing.JMenu Umbralizacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5_Name;
    public javax.swing.JLabel jLabel6_Altura;
    public javax.swing.JLabel jLabel7_Ancho;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem10_Suma;
    public javax.swing.JMenuItem jMenuItem11_Resta;
    public javax.swing.JMenuItem jMenuItem12_And;
    public javax.swing.JMenuItem jMenuItem13_Or;
    public javax.swing.JMenuItem jMenuItem14_Xort;
    public javax.swing.JMenuItem jMenuItem15_Rotacion90;
    public javax.swing.JMenuItem jMenuItem16_Rotacion180;
    public javax.swing.JMenuItem jMenuItem17_Rotacion270;
    public javax.swing.JMenuItem jMenuItem1_Espectro;
    public javax.swing.JMenuItem jMenuItem1_Interpolacion;
    public javax.swing.JMenuItem jMenuItem1_Inverso;
    public javax.swing.JMenuItem jMenuItem1_Media_Adaptativo;
    public javax.swing.JMenuItem jMenuItem1_Media_Aritmetica;
    public javax.swing.JMenuItem jMenuItem1_butterworthBandPassFilter;
    public javax.swing.JMenuItem jMenuItem1_butterworthBandStopFilter;
    public javax.swing.JMenuItem jMenuItem1_butterworthHighPassFilter;
    public javax.swing.JMenuItem jMenuItem1_butterworthLowPassFilter;
    public javax.swing.JMenuItem jMenuItem1_idealBandPassFilter;
    public javax.swing.JMenuItem jMenuItem1_idealBandStopFilter;
    public javax.swing.JMenuItem jMenuItem1_idealHighPassFilter;
    public javax.swing.JMenuItem jMenuItem1_idealLowPassFilter;
    public javax.swing.JMenuItem jMenuItem2_Convolucion;
    public javax.swing.JMenuItem jMenuItem2_Media_Geometrica;
    public javax.swing.JMenuItem jMenuItem2_Operador_Umbral;
    public javax.swing.JMenuItem jMenuItem3_Mediana;
    public javax.swing.JMenuItem jMenuItem3_Operador_Umbral_Inverso;
    public javax.swing.JMenuItem jMenuItem4_Binario;
    public javax.swing.JMenuItem jMenuItem4_Maximo;
    public javax.swing.JMenuItem jMenuItem5_Binario_Inverso;
    public javax.swing.JMenuItem jMenuItem5_Minimo;
    public javax.swing.JMenuItem jMenuItem6_Punto_Medio;
    public javax.swing.JMenuItem jMenuItem6_Umbral_Gris;
    public javax.swing.JMenuItem jMenuItem7_Media_Seccion;
    public javax.swing.JMenuItem jMenuItem7_Umbral_Gris_Inverso;
    public javax.swing.JMenuItem jMenuItem8_Operador_Extencion;
    public javax.swing.JMenuItem jMenuItem9_Reduccion_Niveles_Gris;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
